language: ruby
cache:
  bundler: true
  apt: true
addons:
  postgresql: '9.4'
  apt:
    packages:
    - zsh
bundler_args: --without production development --deployment --jobs=3 --retry=3
before_install:
  - export TZ=Europe/Zurich
before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
    - cp config/database.travis.yml config/database.yml
    - cp config/application.travis.yml config/application.yml
    - cp spec/code_climate.travis.rb spec/code_climate.rb
script: bin/check

