# Run bin/setup to configure the hostname for your local dev env
APP_HOST: 'renuo-cms-api.dev'
APP_PORT: '3000'

# Secrets
SECRET_KEY_BASE: 'rake secret'

# Newrelic
NEW_RELIC_LICENSE_KEY: 'TODO'
NEW_RELIC_APP_NAME: 'renuo-cms-api-<branch>'

# Add 3 new projects for develop/master/testing at https://app.getsentry.com/organizations/renuo/projects/new/
SENTRY_DSN: ''
